[
    {'text': 'Translating high-level languages ', 'hint': '', 'note': '', 'answer': 'to low-level code that a processor can understand requires the compiler.', 'root': True, 'disabled': False, 'blankFill': True, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
    {'text': 'Converting from low-level languages ', 'hint': '', 'note': '', 'answer': 'to machine code requires an assembler.', 'root': True, 'disabled': False, 'blankFill': True, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
    {'text': 'Java:', 'hint': '', 'note': '', 'answer': 'Java:', 'root': True, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': [
        {'text': 'Allows the programmer to keep code hidden by only distributing the bytecode.', 'hint': '', 'note': '', 'answer': 'Allows the programmer to keep code hidden by only distributing the bytecode.', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Comments are notes to the reader or programmer that help to improve readability.', 'hint': '', 'note': '', 'answer': 'Comments are notes to the reader or programmer that help to improve readability.', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Statements perform an action and are terminated by a semicolon.', 'hint': '', 'note': '', 'answer': 'Statements perform an action and are terminated by a semicolon.', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'A program block is a group of statements delimited by curly brackets.', 'hint': '', 'note': '', 'answer': 'A program block is a group of statements delimited by curly brackets.', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Methods are a named collection of statements that perform a task.', 'hint': '', 'note': '', 'answer': 'Methods are a named collection of statements that perform a task.', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Classes are programs representing a particular activity.', 'hint': '', 'note': '', 'answer': 'Classes are programs representing a particular activity.', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}]}, 
    {'text': 'Java Program: ', 'hint': '', 'note': '', 'answer': 'public class Filename { public static void main(String[] args) { // Program } }', 'root': True, 'disabled': False, 'blankFill': True, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
    {'text': 'Programming Points:', 'hint': '', 'note': '', 'answer': 'Programming Points:', 'root': True, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': [
        {'text': 'Precondition -> When should the program work?', 'hint': '', 'note': '', 'answer': 'Precondition -> When should the program work?', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Input -> Does the program need any data?', 'hint': '', 'note': '', 'answer': 'Input -> Does the program need any data?', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Calculations -> What should the program calculate?', 'hint': '', 'note': '', 'answer': 'Calculations -> What should the program calculate?', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Output -> Does the program return any results?', 'hint': '', 'note': '', 'answer': 'Output -> Does the program return any results?', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}, 
        {'text': 'Postcondition -> What is the state after execution?', 'hint': '', 'note': '', 'answer': 'Postcondition -> What is the state after execution?', 'root': False, 'disabled': False, 'blankFill': False, 'title': False, 'order': None, 'marker': {'leniency': 90, 'equation': False, 'markBrackets': True, 'markPunc': True, 'markSpaces': False, 'markCase': False, 'markNumbers': False}, 'points': []}]}
]